# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ name_of_your_branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Load cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules

      - name: Install dependencies
        run: npm install

      - name: Build App
        run: npm run build:ts

      - name: Generate deployment package
        run: zip -r --symlinks deploy.zip . -x node_modules/\* *.git*

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        env:
          VERSION_LABEL: name_of_your_label-${{ github.run_id }}
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: name_of_your_application_aws
          environment_name: name_of_your_environment_aws
          version_label: ${{ env.VERSION_LABEL }}
          region: eu-west-1
          deployment_package: deploy.zip
